services:
  - type: web
    name: hospital-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_vGY2bagywA3c@ep-damp-paper-ajt8kth1-pooler.c-3.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
